// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function AddAllowRule(arg1:string,arg2:string,arg3:boolean):Promise<main.RulesView>;

export function AddBlockRule(arg1:string,arg2:boolean):Promise<main.RulesView>;

export function AddFocusSite(arg1:string):Promise<void>;

export function AddKeyword(arg1:string):Promise<void>;

export function CACertPath():Promise<string>;

export function ClearStats():Promise<void>;

export function ConfirmQuit(arg1:string):Promise<void>;

export function DisableProtection(arg1:string):Promise<void>;

export function EnableProtection():Promise<void>;

export function GetAdvancedSettings():Promise<main.AdvancedSettings>;

export function GetContentSettings():Promise<main.ContentSettings>;

export function GetDisableDelayStatus():Promise<main.DisableDelayStatus>;

export function GetFocusMode():Promise<main.FocusModeStatus>;

export function GetFocusSites():Promise<Array<config.FocusSite>>;

export function GetKeywords():Promise<main.KeywordsData>;

export function GetLanguage():Promise<string>;

export function GetLevelCategories():Promise<Record<string, Array<string>>>;

export function GetProxySettings():Promise<main.ProxySettings>;

export function GetRules():Promise<main.RulesView>;

export function GetStatus():Promise<main.Status>;

export function GetTimeRestrictions():Promise<config.TimeRestrictions>;

export function HasPassword():Promise<boolean>;

export function InstallCACert():Promise<void>;

export function ReloadSettings():Promise<main.DiagnosticsView>;

export function RemoveAllowRule(arg1:string):Promise<main.RulesView>;

export function RemoveBlockRule(arg1:string,arg2:string):Promise<main.RulesView>;

export function RemoveFocusSite(arg1:string):Promise<void>;

export function RemoveKeyword(arg1:string):Promise<void>;

export function RequestDisable():Promise<void>;

export function RetryHosts():Promise<main.ApplyView>;

export function SaveAdvancedSettings(arg1:string,arg2:main.AdvancedSettings):Promise<void>;

export function SaveContentSettings(arg1:string,arg2:main.ContentSettings):Promise<void>;

export function SaveProxySettings(arg1:main.ProxySettings):Promise<void>;

export function SaveTimeRestrictions(arg1:config.TimeRestrictions):Promise<void>;

export function SetFilterLevel(arg1:string):Promise<void>;

export function SetFocusSiteActive(arg1:string,arg2:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetPassword(arg1:string,arg2:string):Promise<void>;

export function SetSafeSearch(arg1:string,arg2:boolean):Promise<void>;

export function StartFocusMode(arg1:number):Promise<void>;

export function StopFocusMode(arg1:string):Promise<void>;

export function Uninstall(arg1:string):Promise<void>;

export function VerifyPassword(arg1:string):Promise<boolean>;
