// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllowRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAllowRule'](arg1, arg2, arg3);
}

export function AddBlockRule(arg1, arg2) {
  return window['go']['main']['App']['AddBlockRule'](arg1, arg2);
}

export function AddFocusSite(arg1) {
  return window['go']['main']['App']['AddFocusSite'](arg1);
}

export function AddKeyword(arg1) {
  return window['go']['main']['App']['AddKeyword'](arg1);
}

export function CACertPath() {
  return window['go']['main']['App']['CACertPath']();
}

export function ClearStats() {
  return window['go']['main']['App']['ClearStats']();
}

export function ConfirmQuit(arg1) {
  return window['go']['main']['App']['ConfirmQuit'](arg1);
}

export function DisableProtection(arg1) {
  return window['go']['main']['App']['DisableProtection'](arg1);
}

export function EnableProtection() {
  return window['go']['main']['App']['EnableProtection']();
}

export function GetAdvancedSettings() {
  return window['go']['main']['App']['GetAdvancedSettings']();
}

export function GetContentSettings() {
  return window['go']['main']['App']['GetContentSettings']();
}

export function GetDisableDelayStatus() {
  return window['go']['main']['App']['GetDisableDelayStatus']();
}

export function GetFocusMode() {
  return window['go']['main']['App']['GetFocusMode']();
}

export function GetFocusSites() {
  return window['go']['main']['App']['GetFocusSites']();
}

export function GetKeywords() {
  return window['go']['main']['App']['GetKeywords']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLevelCategories() {
  return window['go']['main']['App']['GetLevelCategories']();
}

export function GetProxySettings() {
  return window['go']['main']['App']['GetProxySettings']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTimeRestrictions() {
  return window['go']['main']['App']['GetTimeRestrictions']();
}

export function HasPassword() {
  return window['go']['main']['App']['HasPassword']();
}

export function InstallCACert() {
  return window['go']['main']['App']['InstallCACert']();
}

export function ReloadSettings() {
  return window['go']['main']['App']['ReloadSettings']();
}

export function RemoveAllowRule(arg1) {
  return window['go']['main']['App']['RemoveAllowRule'](arg1);
}

export function RemoveBlockRule(arg1, arg2) {
  return window['go']['main']['App']['RemoveBlockRule'](arg1, arg2);
}

export function RemoveFocusSite(arg1) {
  return window['go']['main']['App']['RemoveFocusSite'](arg1);
}

export function RemoveKeyword(arg1) {
  return window['go']['main']['App']['RemoveKeyword'](arg1);
}

export function RequestDisable() {
  return window['go']['main']['App']['RequestDisable']();
}

export function RetryHosts() {
  return window['go']['main']['App']['RetryHosts']();
}

export function SaveAdvancedSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveAdvancedSettings'](arg1, arg2);
}

export function SaveContentSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveContentSettings'](arg1, arg2);
}

export function SaveProxySettings(arg1) {
  return window['go']['main']['App']['SaveProxySettings'](arg1);
}

export function SaveTimeRestrictions(arg1) {
  return window['go']['main']['App']['SaveTimeRestrictions'](arg1);
}

export function SetFilterLevel(arg1) {
  return window['go']['main']['App']['SetFilterLevel'](arg1);
}

export function SetFocusSiteActive(arg1, arg2) {
  return window['go']['main']['App']['SetFocusSiteActive'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetPassword(arg1, arg2) {
  return window['go']['main']['App']['SetPassword'](arg1, arg2);
}

export function SetSafeSearch(arg1, arg2) {
  return window['go']['main']['App']['SetSafeSearch'](arg1, arg2);
}

export function StartFocusMode(arg1) {
  return window['go']['main']['App']['StartFocusMode'](arg1);
}

export function StopFocusMode(arg1) {
  return window['go']['main']['App']['StopFocusMode'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['main']['App']['Uninstall'](arg1);
}

export function VerifyPassword(arg1) {
  return window['go']['main']['App']['VerifyPassword'](arg1);
}
